apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-funqy-jvm
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/moses-286120/quarkus-funqy-knative:1
          env:
            - name: TARGET
              value: "v1"
