apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-knative-native
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/moses-286120/quarkus-knative-native:1
          env:
            - name: TARGET
              value: "v1"
